---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-cluster-data-1
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: postgres-cluster-data-1
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-cluster-data-2
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: postgres-cluster-data-2
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-cluster-data-3
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: postgres-cluster-data-3
    fsType: ext4
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-cluster-data-1-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-cluster-data-2-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-cluster-data-3-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi