apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-sentinel-rc
  annotations:
    description: Postgres HA
    contact: Michael Bishop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: stolon-sentinel
  template:
    metadata:
      labels:
        name: stolon-sentinel
        stolon-cluster: "kube-stolon"
        stolon-sentinel: "true"
      annotations:
        description: Postgres HA
        contact: Michael Bishop
    spec:
      containers:
      - name: stolon-sentinel
        image: sorintlab/stolon:latest
        env:
          - name: SENTINEL
            value: "true"
          - name: STSENTINEL_CLUSTER_NAME
            value: "kube-stolon"
          - name: STSENTINEL_STORE_BACKEND
            value: "etcd" # Or consul
          - name: STSENTINEL_STORE_ENDPOINTS
            value: "10.245.1.1:2379"
          - name: STSENTINEL_KEEPER_KUBE_LABEL_SELECTOR
            value: "stolon-cluster=kube-stolon,stolon-keeper=true"
            # Enable debugging
          - name: STSENTINEL_DEBUG
            value: "true"
          - name: STSENTINEL_KUBERNETES_NAMESPACE
            value: "default"
        ports:
          - containerPort: 6431
        resources:
          requests:
            memory: "1Gi"
            cpu: 0.5
          limits:
            memory: "2Gi"
            cpu: 1.5
