apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: stolon-keeper-rc
  annotations:
    description: Postgres HA
    contact: Michael Bishop
spec:
  replicas: 1
  selector:
    name: stolon-keeper
  template:
    metadata:
      labels:
        name: stolon-keeper
        stolon-cluster: "kube-postgres"
        stolon-keeper: "true"
      annotations:
        description: Postgres HA
        contact: Michael Bishop
    spec:
      containers:
      - name: stolon-keeper
        image: sorintlab/stolon:latest
        env:
          - name: KEEPER
            value: "true"
          - name: STKEEPER_CLUSTER_NAME
          # TODO(sgotti) Get cluster name from "stoloncluster" label using a downward volume api instead of duplicating the name here
            value: "kube-postgres"
          - name: STKEEPER_STORE_BACKEND
            value: "consul" # Or consul
          - name: STKEEPER_STORE_ENDPOINTS
            value: "consul.corp.advisorconnect.co:8500"
            # Enable debugging
          - name: STKEEPER_DEBUG
            value: "true"
          - name: STKEEPER_INITIAL_PG_SU_USERNAME
            value: "postgres"
          - name: STKEEPER_INITIAL_PG_SU_PASSWORD_FILE
            value: "/etc/secrets/stolon/password"
        ports:
          - containerPort: 5431
          - containerPort: 5432
        resources:
          requests:
            memory: "24Gi"
            cpu: 6
          limits:
            memory: "32Gi"
            cpu: 12
        volumeMounts:
        - mountPath: /stolon-data
          name: data
        - mountPath: /etc/secrets/stolon
          name: stolon
      volumes:
        - name: data
          persistentVolumeClaim:
            pdName: postgres-cluster-data-1-claim
            fsType: ext4
        - name: stolon
          secret:
            secretName: stolon
